### PR TITLE
Add `import-esm` flag

### LINKED ISSUE #152: Feature Request l ESM .js extension
Add a feature flag that enables ESM relative imports with file extensions ending in "`.js`"

Before:
```ts
import { A } from "./B";
```
After (e.g. `esm` feature flag):
```ts
import { A } from "./B.js";
```

The implementation of this should be simple.

### PR DESCRIPTION
**Pull request by escritorio-gustavo**
Add a feature flag called `import-esm` to add the `.js` extension at the end of file paths in TS `import` statements

Fixes #152

### CODE REVIEW

**Comment by NyxCode** [comment]
Hey, thanks for the PR. I think this is a good change, though I'm growing more and more uncomfortable by cargo features being the only way to really configure anything. That being said, I don't see any better option right now.  

Could you move the changes from the README.md into the doc comment in ts-rs/lib.rs, and generate the README as described in CONTRIBUTING.md?

**Comment by escritorio-gustavo** [comment]
> Could you move the changes from the README.md into the doc comment in ts-rs/lib.rs, and generate the README as described in CONTRIBUTING.md?
Done, sorry I totally skipped on reading it.

> I'm growing more and more uncomfortable by cargo features being the only way to really configure anything.
I see... there really are a lot of cargo features going on. For this specific PR it's probably the only way to go due to ESM imports being kind of a global config on the TS side, but for future PRs what do you think should be the way to go?

**Comment by NyxCode** [comment]
I've added a check in the CI pipeline for that, so that we dont miss that in the future.

**Comment by NyxCode** [comment]
I had to re-generate the README since the encoding (remote: UTF-8, branch: UTF16-LE) differed. Idk where that happened, but I guess we'll figure that out on the next PR.

**Comment by escritorio-gustavo** [comment]
It seems to be my computer. Whenever I run the `cargo readme` command the README decides to double in size

**Pull request merged**
