### PR TITLE
Add dependency caching to GH Actions for faster CI

### PR DESCRIPTION
**Pull request by escritorio-gustavo**
Our CI takes quite a while to run, mostly because of the Rust compiler being kinda slow. This PR attempts to remedy that by caching its dependencies. It also runs twice on every commit when we do PR's from within the repo, this PR also fixes that.

I have no idea if it will actually work, but should be worth the shot

### CODE REVIEW

**Comment by escritorio-gustavo** [comment]
Okay, first CI run finished in 2m 30s.

We have a few dead code warnings in our tests, I'll add `#![allow(dead_code)]` to remove those and trigger CI so we can see if there is a difference

**Comment by escritorio-gustavo** [comment]
2m 22s... that's disappointing

**Comment by escritorio-gustavo** [comment]
I think it's not caching because it has to compile both `--all-features` and `--no-default-features`. I'll try splitting them up to see if helps, if it doesn't, I'll just close this PR

**Comment by escritorio-gustavo** [comment]
Oops, running these tests in parallel breaks them due to everyone messing with the same files

**Comment by escritorio-gustavo** [comment]
> Instead of running serially, stop CI from running twice

Insetead of this, I stopped CI from running at all smh

**Comment by escritorio-gustavo** [comment]
This is not gonna work

**Comment by escritorio-gustavo** [comment]
Hold on, it seems I still have a syntax error

**Comment by escritorio-gustavo** [comment]
Well, I finally got CI to run again

**Comment by escritorio-gustavo** [comment]
It is about 30-40 seconds faster, but recompilation is still happenning, I'll try changing `CARGO_HOME`

**Comment by escritorio-gustavo** [comment]
Finally! Got the time down to 56s

**Comment by escritorio-gustavo** [comment]
> Finally! Got the time down to 1m06s

The only reason for it to still be this slow is that the `--all-features` test still takes 40s+ to compile for some reason... still, better than the previous 2m+

**Review by NyxCode — APPROVED** [review]
> It also runs twice on every commit when we do PR's from within the repo, this PR also fixes that.

🥳

Great change, super happy to see this!  
To keep main clean, it'd be nice if you could squash the commits.

**Pull request merged**
