### PR TITLE
Generics support (part III)

### LINKED ISSUE #14: Support for generics
```rs
#[derive(TS)]
struct A<T> {
    foo: String,
}
```

Results in the following error:

```
wrong number of type arguments: expected 1, found 0
expected 1 type argument
```

I suspect this error is triggered somewhere in the macro implementation, though I don't see where exactly. What would it take for generics to be supported? If I had a few pointers I might try to see if I could implement it myself.

### PR DESCRIPTION
**Pull request by arendjr**
This is the latest PR for applying generics support. It fixes #14 and #22 and supersedes #18.

Generics are now supported, which includes generic structs such as `MyStruct<T>` and generic arguments to existing containers such as `Vec<MyItem>`.

It also contains a few minor fixes as described in #22.

### CODE REVIEW

**Comment by marjakm** [comment]
I added a bit on top of your branch @arendjr 

This commit https://github.com/bislydev/ts-rs/commit/d7afa2f1881199f27a5c8b97254d0b4325ab94f4

Makes this work:

```rust
#[derive(TS)]
struct Generic2<T> {
    value: T,
    values: Vec<T>,
}
```

Without it, you had to do this (but in rust you dont ususally add type bounds to data):

```rust
#[derive(TS)]
struct Generic<T>
where
    T: TS,
{
    value: T,
    values: Vec<T>,
}
```

That commit can be improved on, it currently only adds bounds when there are none, but it could also insert bounds if there already are some. This branch could be implemented https://github.com/bislydev/ts-rs/commit/d7afa2f1881199f27a5c8b97254d0b4325ab94f4#diff-4feb5862b96e70d6a225028210762f9a2d19ea5e35860fe78d211fb607c82b26R82

I'm a bit busy at the moment, but could help with implementing it at some later time

**Comment by NyxCode** [comment]
Hm, how should we procede with this? I'd happily merge this as-is, or should we wait for @marjakm additions?

**Comment by marjakm** [comment]
I created a pull request to the @arendjr branch this pull request is based on. https://github.com/arendjr/ts-rs/pull/1
You could also just merge this as-is and I could make the pull request against this repo.

**Comment by arendjr** [comment]
Nice job! I’ve merged. Just need to resolve some conflicts, I see.

**Comment by arendjr** [comment]
All merged, and tests passed. Should be good to go!

**Comment by NyxCode** [comment]
Finally! 😉 Thanks for your awesome work, and sorry that it took so long.

**Comment by NyxCode** [comment]
0.4 is out!

**Comment by NyxCode** [comment]
@arendjr I found a regresion when using a generic type within `Option`:
```rust
    #[derive(TS)]
    struct List {
        data: Option<Vec<u32>>
    }
```
results in 
```ts
interface List {
  data: Array | null
}
```

**Comment by NyxCode** [comment]
I have not gone super deep into the implementation, but I would guess that Option should now be implemented like this:
```rust
impl<T: TS> TS for Option<T> {
    fn name() -> String {
        unreachable!();
    }

    fn name_with_type_args(args: Vec<String>) -> String {
        assert_eq!(args.len(), 1);
        format!("{} | null", args[0])
    }
}

**Comment by arendjr** [comment]
You're right, that seems indeed the proper fix. Thanks!

**Pull request merged**
