### PR TITLE
Add smallvec support

### PR DESCRIPTION
**Pull request by HactarCE**

### CODE REVIEW

**Comment by NyxCode** [comment]
thanks! can you also update the documantation like [this](https://github.com/Aleph-Alpha/ts-rs/blob/main/CONTRIBUTING.md#documentation)?

**Comment by HactarCE** [comment]
Done! Anything else?

**Comment by escritorio-gustavo** [comment]
Can you resolve the merge conflict and run `cargo readme` again?

**Comment by escritorio-gustavo** [comment]
One more thing, can you add sme tests for this feature in the `ts-rs/tests` directory?

**Comment by escritorio-gustavo** [comment]
This has been stale for some time, and `#[ts(as = "Vec<T>")]` is probably a drop in replacement for this so I'll close this for now. If there is still interest in this, feel free to reopen the PR and merge main into your branch to resolve the merge conflicts

**Pull request closed without merging**
