### PR TITLE
Add test for `rename_all` on enum struct variants

### PR DESCRIPTION
**Pull request by escritorio-gustavo**
Added test requested in this thread: https://github.com/Aleph-Alpha/ts-rs/issues/135#issuecomment-1902162740

Fixed version of #196

### CODE REVIEW

**Comment by escritorio-gustavo** [comment]
I seem to be really bad at making these PRs the first one included wrong code and this seems to include nothing at all smh

**Comment by NyxCode** [comment]
😄 All good, thanks for the PR!
I really like that we are accumulating loads of test. Really helps with making changes when there's confidence that we didnt break anything important.

**Comment by escritorio-gustavo** [comment]
Yeah, I was kind of scared of making the #199 PR until I ran `cargo test` and nothing failed xD

**Comment by NyxCode** [comment]
At least I really have to rely on the test suite at this point. No way I can look at a piece of code and understand all of its implications.

**Pull request merged**
