### PR TITLE
Support `#[ts(as = "...")]` and `#[ts(type = "...")]` on enum variants

### PR DESCRIPTION
**Pull request by escritorio-gustavo**
## Goal

Add support for using  `#[ts(as = "...")]` and `#[ts(type = "...")]` on enum variants to make support for `#[serde(with = "...")]` (#280) possible here too

## Changes

`#[ts(as = "...")]` and `#[ts(type = "...")]` are now parsed and processed in enum variants.

Using them currently respects the tag enum representation. That is, neither `#[ts(as = "...")]` nor `#[ts(type = "...")]` will eliminate the "tag" or "content" properties the variant would have without them, as that can be achieved by using `#[ts(untagged)]` on the variant. I don't yet know if this is how serde works, so this can be changed to maintain serde compatibility

## Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/Aleph-Alpha/ts-rs/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by escritorio-gustavo** [comment]
I may need some help on the tests for this. I can't even get `#[serde(with = "...")]` on variants to compile atm

**Comment by NyxCode** [comment]
would love to take a loot at this once i find some time 👍

**Comment by escritorio-gustavo** [comment]
@NyxCode, I think I figured out how `#{serde(with = ...)]` is used in variants. Looking at the last commit, do you think the current behavior of `#[ts(as = ...)]` is correct? I think it is, but I still don't quite understand `#{serde(with = ...)]` deeply enough to be sure

**Comment by JonasFocke01** [comment]
I tested my usecase from #352 and can confirm that this works as expected

**Comment by gustavo-shigueo** [comment]
Hi @JonasFocke01, I've just fixed a merge conflict and caused a couple of compiler errors in the process, can you check if it still works?

**Comment by JonasFocke01** [comment]
@gustavo-shigueo Workds still as expected :+1:

**Review by NyxCode — APPROVED** [review]
nicely done!

**Pull request merged**
