### PR TITLE
Support serde's "rename_all" on enum variants

### PR DESCRIPTION
**Pull request by phoneticsushi**
Adds tests and implementation resolving #72 and #119, though the latter was already working AFAICT.

### CODE REVIEW

**Comment by phoneticsushi** [comment]
This PR is failing tests, but that same commit ([a6825f3](https://github.com/Aleph-Alpha/ts-rs/pull/122/commits/a6825f3fcc442243406e0dae257d8bb04ac1d35a)) passes `cargo clean; cargo test` on my machine and correctly generates typescript files in camelCase when included as a dependency of a separate project.  Any suggestions are appreciated

**Comment by NyxCode** [comment]
Hey!
The issue seems to be that the test is run once with `cargo t` and once with `cargo t --no-default-features`.  
I'd recommend you 
1. not only test the `#[serde(..)]` annotations, but also the equivalend `#[ts(..)]` annotations.
2. Put tests which rely on the `serde-compat` feature behind a `#[cfg(feature = "serde-compat")]` gate

**Comment by NyxCode** [comment]
For example, this would do the trick:
```rust
    #[cfg_attr(feature = "serde-compat", serde(rename_all = "camelCase"))]
    #[cfg_attr(not(feature = "serde-compat"), ts(rename_all = "camelCase"))]
    ```

**Comment by NyxCode** [comment]
let me just merge this as-is and apply the minor fix to the tests. Thanks, really appreciate it!

**Pull request merged**
